### ISSUE TITLE
Drag-n-drop support

### ISSUE THREAD

**Issue by greenozon** [mrfearless/MediaPlayer#4]
Not sure how exactly it works now, it seems try to accept dropped media files, but then nothing happens
seen when something is playing and you drop over media file

Another nice to have & user-friendly feature :)

**Comment by greenozon** [comment]
after some d-n-d games I hit the silent crash ....

pic from dump:


![image](https://github.com/user-attachments/assets/57f050e4-8fbf-417f-a156-6a3c2eafbed4)

**Comment by mrfearless** [comment]
Ok, thanks for letting me know. I will look into this further. In theory it should work like the main screen when first loaded, accepting drag and drop, checking if a file is already playing, stopping it, releasing the media item, then processing the dropped file, setting the title etc, setting it in the queue and then playing it. Its possible that something isn't being taken into account properly somewhere. If you are able to reproduce it exactly that might help, otherwise it may be some handles or memory being leaked somewhere if its more random and hard to pin down.

**Comment by greenozon** [comment]
again, everything is all around this.. - https://github.com/mrfearless/MediaPlayer/issues/2
you could skip it if it's not planned

**Comment by mrfearless** [comment]
Found that I wasn't calling DragFinish after calls to DragQueryFile, so a memory leak there. Should be fixed in next version which will have Unicode support, which should also fix some of the issues raised.

**Comment by greenozon** [comment]
are there any plans for releasing patch build soon?

**Comment by mrfearless** [comment]
Let me know if the latest version resolves some of these issues, and if so we can then close them. Thanks.

**Comment by greenozon** [comment]
great news! I'll try to test it out today and get back

**Comment by greenozon** [comment]
tested, can't reproduce
conclusion: well done!
closing
